# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'RBQFetchedResultsControllerSwiftExample' do

use_frameworks!
pod 'RBQFetchedResultsController'
pod 'Realm'

end

target 'RBQFetchedResultsControllerSwiftExampleTests' do

end

